### ISSUE TITLE
✨ 3.0.0 코스를 상세하게 보여주는 피드 만들기 (resuable)

### ISSUE THREAD

**Issue by luminouxx** [DeveloperAcademy-POSTECH/MacC-Team-Trying-iOS#10]
## 💬 Description

<img width="300" alt="스크린샷 2022-10-12 오후 2 41 40" src="https://user-images.githubusercontent.com/81943525/195261428-18fa7ee8-8098-4ead-b29f-c56e5f327564.png">

+ 위의 친구를 만들 예정입니다.
+ 1,2번 탭에서도 쓰일 것 같군요 ㅎ

## 📝 Todo
- [ ] 3.0.0 코스상세뷰 UI구현

## ETC
- 화이팅!

**Comment by LentoAssai** [comment]
Moya?
Merge?

**Comment by wody-d** [comment]
화이팅!

**Comment by kyustudyo** [comment]
Thanks for the assigning bro. you are the best

**Comment by luminouxx** [comment]
Thanks
