### ISSUE TITLE
✨[UI] TicketView UI구성

### ISSUE THREAD

**Issue by luminouxx** [DeveloperAcademy-POSTECH/MacC-Team-Trying-iOS#113]
## 💬 Description

+ TicketView를 만들겠습니다.
<img width="281" alt="스크린샷 2022-11-07 오전 10 46 14" src="https://user-images.githubusercontent.com/81943525/200210065-bab7fe1f-73e1-4715-b549-ddd25858fc24.png">

## 📝 Todo
- [ ] TicketView 화면전환
- [ ] TicketView UI구성

**Comment by LentoAssai** [comment]
진짜 제목 킹받네요
