### ISSUE TITLE
✨마이페이지 새출발

### ISSUE THREAD

**Issue by kyustudyo** [DeveloperAcademy-POSTECH/MacC-Team-Trying-iOS#116]
## 💬 Description
아래 컴포넌트

## 📝 Todo
<img width="228" alt="스크린샷 2022-11-07 오후 4 53 04" src="https://user-images.githubusercontent.com/77485339/200255325-5c47504d-80ab-40c6-aff2-81a09ce4ea1e.png">
<img width="313" alt="스크린샷 2022-11-07 오후 4 54 20" src="https://user-images.githubusercontent.com/77485339/200255517-ce3e470b-7441-42bf-a33c-730e7eddd583.png">

- [ ] Todo

**Comment by LentoAssai** [comment]
<img width="415" alt="스크린샷 2022-11-07 20 52 52" src="https://user-images.githubusercontent.com/88371913/200303694-2c9ca6fb-b139-49b8-8d06-2680a2060cf1.png">
제가 해치웠습니다
