### ISSUE TITLE
🆘  UICollectionView IndexPath 관련 [Help!!!]

### ISSUE THREAD

**Issue by luminouxx** [DeveloperAcademy-POSTECH/MacC-Team-Trying-iOS#143]
### 현재 상황
---

#### feat/133-LogHomeViewUI

LogHomeViewController에
> PreviousConstellationButton
> CurrentConstellationButton
> NextConstellationButton     
#### 위 3가지 버튼이 있습니다. (아래 이미지 참조)
<img width="351" alt="스크린샷 2022-11-13 오후 2 09 56" src="https://user-images.githubusercontent.com/81943525/201506880-45943a6f-10a9-4dc6-ad30-45fb9c7d6ae3.png">

#### LogHomeViewController.swift
```swift
private var currentIndex: Int = 0 {
        didSet {
            setConstellationButtonOption()
        }
    }
```
LogHomeViewController는 currentIndex라는 변수를 가집니다.
초기 값은 0으로 초기화 되어있으며, currentIndex가 바뀌는 경우는
3가지 입니다.

## 1. 이전버튼과 , 다음 버튼을 눌렀을 경우
```swift
@objc
    func tapPreviousConstellationButton() {
        print("tapPreviousConstellationButton tappped")
        currentIndex -= 1
        logCollectionView.scrollToItem(at: IndexPath(row: currentIndex, section: 0), at: .bottom, animated: true)
    }
```
```swift
@objc
    func tapNextConstellationButton() {
        print("tapNextConstellationButton tappped")
        currentIndex += 1
        logCollectionView.scrollToItem(at: IndexPath(row: currentIndex, section: 0), at: .left, animated: true)
    }
```

### 2. CollectionView Delegate -> cellForItemAt
```swift
func collectionView(_ collectionView: UICollectionView, cellForItemAt indexPath: IndexPath) -> UICollectionViewCell {
        guard let cell = collectionView.dequeueReusableCell(withReuseIdentifier: LogCollectionViewCell.identifier, for: indexPath) as? LogCollectionViewCell else { return UICollectionViewCell() }
        cell.courseNameLabel.text = viewModel.courses[indexPath.row].courseName
        cell.configure(with: viewModel.courses[indexPath.row].places)
        currentIndex = indexPath.row
        return cell
    }
```
> 문제는 바로 이녀석입니다.
> 다음 셀을 준비하는 메소드인 것으로 아는데 첫번째 셀과 마지막 셀에서 2개씩 건너뛰는 문제가 있습니다.
> collectionView Cell의 현재 indexPath를 알 수 있는 방법을 아시는 분이 있으면 알려주세요

### 영상
> 버튼을 눌러서 화면전환은 잘 됩니다.

![Nov-13-2022 14-17-49](https://user-images.githubusercontent.com/81943525/201507048-6e80b9ab-8dd2-4165-a6ed-fc89ed4afff0.gif)

> CollectionView Cell을 전환했을때 이슈가 있습니다.

![Nov-13-2022 14-20-20](https://user-images.githubusercontent.com/81943525/201507122-ebb4d2b3-9186-41a4-9e03-de805927666d.gif)

@LentoAssai @wody-d @kimscastle @kyustudyo 
혼자 해결해보려고 했으나 더 끌고 있으면 민폐인 것 같아서 이슈에 올려봅니다.

**Comment by LentoAssai** [comment]
#144

**Comment by kimscastle** [comment]
일단 별자리 추가 버튼은 고정되어있는게 맞는거같은데

**Comment by kimscastle** [comment]
그 indexPath를 max함수써서 마지막 indexPath이후로는 .count값으로 고정시키면 indexpath가 count이상으로 올라가지 않을거같은데

**Comment by luminouxx** [comment]
현재 min, max를 적용해 두었습니다....

**Comment by wody-d** [comment]
currentIndex를 왜 cellForRowAt메소드에서 설정했는 지 이유를 알 수 있을가여? 

> collectionView Cell의 현재 indexPath를 알 수 있는 방법을 아시는 분이 있으면 알려주세요

ScrollViewDeleagte 프로토콜 안에 메소드를 이용해서 구할 수 있음 현재 collectionView가 페이징 속성이 설정되어있는지도 궁금하네요.

**Comment by luminouxx** [comment]
페이징 속성은 설정했습니다.
ScrollView의 Delegate 메소드에서 해결을 했어용
습관적으로 CellForRow에서 그랬던 것 같습니다 우디
고멘나사이!
