### ISSUE TITLE
✨Coordinator 프레임 잡기

### ISSUE THREAD

**Issue by LentoAssai** [DeveloperAcademy-POSTECH/MacC-Team-Trying-iOS#5]
## 💬 Description
Coordinator패턴을 사용하기 위해 틀을 잡습니다.

## 📝 Todo
- [x] Coordinator 프로토콜 생성
- [x] AppCoordinator 생성
- [x] LoginCoordinator, MainCoordinator 생성
- [x] AppDelegate 수정

**Comment by wody-d** [comment]
데이터 전달도 고려부탁드려요~

**Comment by luminouxx** [comment]
혹시 공부할 리소스 추천해줄 수 있나요

**Comment by LentoAssai** [comment]
@wody-d 
데이터 전달.. 그냥 코디네이터로 전달하는 방법도 많이 쓰는거같은데..
일단 더 알아보고 최선을 다해볼게유

@luminouxx 
내 [블로그](https://velog.io/@tmdckd232)에서 글은 보지마시고 맨 밑에 Reference 보시면 됩니당

**Comment by luminouxx** [comment]
넹 오늘 볼게용
