### ISSUE TITLE
✨[UI] (3.2.0) 지도 기반의 코스 뷰 UI구성

### ISSUE THREAD

**Issue by luminouxx** [DeveloperAcademy-POSTECH/MacC-Team-Trying-iOS#75]
## 💬 Description

<img width="208" alt="스크린샷 2022-10-24 오후 2 57 39" src="https://user-images.githubusercontent.com/81943525/197457522-9edded92-c6d8-4a2b-b9a4-49e34eb003cb.png">
> @LentoAssai 와 함꼐 지도 부분을 맡게 되었고, 일단은 MapKit을 사용해서 구현할 예정입니다.
> UI Componet & layout만 일단 맞출 예정입니다.

## 📝 Todo
- [ ] UI 구성

**Comment by LentoAssai** [comment]
저와 함께 두근두근 데이트 해보시죠
