### ISSUE TITLE
[기능] Home화면 UI구현

### ISSUE THREAD

**Issue by kimscastle** [DeveloperAcademy-POSTECH/MacC-Team-Trying-iOS#8]
## 💬 Description
HomeView 구현작업

## 📝 Todo
- [x] #9
- [ ] "1.0.0 내 행성"에서 "1.1.0 내 위성"으로 넘어가는 애니메이션 구현
- [x] #60
- [x] #44

**Comment by wody-d** [comment]
난 리뷰어로 참가하기 때문에 Assign 한건가?

**Comment by wody-d** [comment]
난 리뷰어로 참가하기 때문에 assign한건가?
